[package]
name = "gitgat"
version = "0.1.0"
edition = "2021"
authors = ["Johan <johangmcquillan@gmail.com@"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.17"
git2 = "0.15.0"
indicatif = "0.17.0"
